// Unexpire passwords for dev mode
zn "%SYS"
do ##class(Security.Users).UnExpireUserPasswords("*")

do ##class(Security.Services).Get("%Service_CallIn",.prop)
set prop("Enabled")=1
set prop("AutheEnabled")=48
do ##class(Security.Services).Modify("%Service_CallIn",.prop)

// create IRISAPP namespace
do $SYSTEM.OBJ.Load("/opt/irisbuild/Installer.cls", "ck") 
set sc = ##class(App.Installer).setup() 

do $System.OBJ.LoadDir("/opt/irisbuild/src","ck",,1)

halt
